version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

volumes:
  db_data: